In [1]:
import gymnasium as gym
import matplotlib.pyplot as plt
from itertools import count

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from Memory import *
from Model import *
from Environment import *
from Strategy import *
from util import *
from args import *
from Environment import *

使用 DEFAULT 作為超參數


In [2]:
policy_net = torch.load('model/policy_net.pth')
target_net = torch.load('model/target_net.pth')

In [3]:
print('最終決策 policy net:')
# Initialize the environment and get it's state
state, _ = env.reset()
#env.displayPosition()
print('-'*10)
state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
for t in count():
    if(t > 100):
        break
    action = policy_net(state).max(1)[1].view(1, 1)
    print(policy_net(state))
    observation, reward, terminated, truncated, _ = env.step(action.item())
    reward = torch.tensor([reward], device=device)
    done = terminated or truncated
    if terminated:
        state = None
    else:
        state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)
    if done:
            episode_durations.append(t + 1)
            total_reward.append(env.TotalReward())
            #plot_durations(total_reward)
            break     
env.displayTotalReward() 
print(env.actionlist)

最終決策 policy net:
----------
tensor([[6.7245, 6.8179]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[6.8206, 6.8930]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[6.8974, 6.9682]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[6.9728, 7.0444]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.0475, 7.1207]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.0915, 6.9449]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.0542, 7.1680]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.1319, 7.0914]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.0730, 7.2118]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.1800, 7.1507]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.1189, 7.2582]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.2229, 7.1769]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.1546, 7.3002]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[7.2680, 7.2501]], device='cuda:0', grad_fn=<AddmmBack

In [4]:
print('最終決策 target net:')
# Initialize the environment and get it's state
state, _ = env.reset()
#env.displayPosition()
print('-'*10)
state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
for t in count():
    print(state)
    if(t > 100):
        break
    action = target_net(state).max(1)[1].view(1, 1)
    print(target_net(state))
    observation, reward, terminated, truncated, _ = env.step(action.item())
    reward = torch.tensor([reward], device=device)
    done = terminated or truncated
    if terminated:
        state = None
    else:
        state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)
    if done:
            episode_durations.append(t + 1)
            total_reward.append(env.TotalReward())
            #plot_durations(total_reward)
            break
env.displayTotalReward()
print(env.actionlist)


最終決策 target net:
----------
tensor([[8., 0.]], device='cuda:0')
tensor([[6.7314, 6.8235]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[9., 1.]], device='cuda:0')
tensor([[6.8282, 6.8990]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[10.,  2.]], device='cuda:0')
tensor([[6.9059, 6.9747]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[11.,  3.]], device='cuda:0')
tensor([[6.9819, 7.0511]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[12.,  4.]], device='cuda:0')
tensor([[7.0573, 7.1276]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[13.,  5.]], device='cuda:0')
tensor([[7.0974, 6.9380]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[12.,  6.]], device='cuda:0')
tensor([[7.0636, 7.1743]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[13.,  7.]], device='cuda:0')
tensor([[7.1388, 7.0881]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[12.,  8.]], device='cuda:0')
tensor([[7.0829, 7.2180]], device='cuda:0', grad_fn=<AddmmBackward0>)
tens