In [10]:
import gymnasium as gym
import matplotlib.pyplot as plt
from itertools import count

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from Memory import *
from Model import *
from Environment import *
from Strategy import *
from util import *
from args import *
from Environment import *

In [12]:
policy_net = torch.load('model/policy_net.pth')
target_net = torch.load('model/target_net.pth')

In [13]:
print('最終決策 policy net:')
# Initialize the environment and get it's state
state, _ = env.reset()
#env.displayPosition()
print('-'*10)
state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
for t in count():
    if(t > 100):
        break
    action = policy_net(state).max(1)[1].view(1, 1)
    print(policy_net(state))
    observation, reward, terminated, truncated, _ = env.step(action.item())
    reward = torch.tensor([reward], device=device)
    done = terminated or truncated
    if terminated:
        state = None
    else:
        state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)
    if done:
            episode_durations.append(t + 1)
            total_reward.append(env.TotalReward())
            #plot_durations(total_reward)
            break     
env.displayTotalReward() 
print(env.actionlist)


print('最終決策 target net:')
# Initialize the environment and get it's state
state, _ = env.reset()
#env.displayPosition()
print('-'*10)
state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
for t in count():
    if(t > 100):
        break
    action = target_net(state).max(1)[1].view(1, 1)
    print(target_net(state))
    observation, reward, terminated, truncated, _ = env.step(action.item())
    reward = torch.tensor([reward], device=device)
    done = terminated or truncated
    if terminated:
        state = None
    else:
        state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)
    if done:
            episode_durations.append(t + 1)
            total_reward.append(env.TotalReward())
            #plot_durations(total_reward)
            break
env.displayTotalReward()
print(env.actionlist)


最終決策 policy net:
----------
tensor([[0.2876, 0.4556]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[0.6095, 0.8062]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[0.9314, 1.1568]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[1.2533, 1.5073]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[1.5753, 1.8579]], device='cuda:0', grad_fn=<AddmmBackward0>)
Total Reward : 0.8
[1, 1, 1, 1, 1]


NameError: name 'i_episode' is not defined